name: Deploy Staging

on:
  push:
    branches:
    - main
    paths:
    - 'wp-content/themes/shiftr/**'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set-up Node.js
      uses: actions/setup-node@v1
    - name: Cache node_modules
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Get deps
      run: npm -s run install-theme-deps
    - name: Compile (unminified)
      run: cd wp-content/themes/shiftr && gulp build
    - name: Deploy to server
      id: deploy
      uses: Pendect/action-rsyncer@v1.1.0
      env:
        DEPLOY_KEY: ${{secrets.STAGING_DEPLOY_KEY}}
      with:
        flags: '-avz --delete'
        options: '--exclude-from $GITHUB_WORKSPACE/.workflow/exclude/deploy-staging.txt'
        ssh_options: ''
        src: '${{ secrets.THEME_DIR }}'
        dest: '${{ secrets.STAGING_USER }}@${{ secrets.STAGING_HOST }}:${{ secrets.STAGING_PATH }}/${{ secrets.THEME_DIR }}'